### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by thevinci** [t3chnoboy/amazon-product-api#29]
I ran a mocha test and everything seems to break.

When I plugged in my credentials from Amazon, I don't get an error but I get results = undefined.

node v0.12.4
amazon-product-api v0.3.4

**Comment by thevinci** [comment]
This is what I get from mocha

  formatQueryParams(query, method, credentials)
    ✓ should return an object
    ItemSearch
      ✓ should use default values
    ItemLookup
      ✓ should use default values
    BrowseNodeLookup
      ✓ should use default values

  generateQueryString(query, method, credentials)
    1) should return a string

  createClient(credentials)
    ✓ should return amazon product api client with item search method

  client.itemSearch(query, cb)
    when credentials are valid
      when no callback is passed
        2) should return search results from amazon
        3) should work with custom domain
      when callback is passed
        4) should return search results from amazon
    when credentials are invalid
      when no callback is passed
        ✓ should return an error (172ms)
      when callback is passed
        ✓ should return an error (137ms)


  7 passing (482ms)
  4 failing

  1) generateQueryString(query, method, credentials) should return a string:
     TypeError: Not a buffer
    at TypeError (native)
    at new Hmac (crypto.js:136:16)
    at Object.Hmac (crypto.js:134:12)
    at generateSignature (lib/utils.js:4:21)
    at generateQueryString (lib/utils.js:106:38)
    at Context.<anonymous> (test/test.coffee:57:21)
  

  2) client.itemSearch(query, cb) when credentials are valid when no callback is passed should return search results from amazon:
     TypeError: Not a buffer
    at TypeError (native)
    at new Hmac (crypto.js:136:16)
    at Object.Hmac (crypto.js:134:12)
    at generateSignature (lib/utils.js:4:21)
    at generateQueryString (lib/utils.js:106:38)
    at Object.itemSearch (lib/index.js:9:15)
    at Context.<anonymous> (test/test.coffee:100:16)
  

  3) client.itemSearch(query, cb) when credentials are valid when no callback is passed should work with custom domain:
     TypeError: Not a buffer
    at TypeError (native)
    at new Hmac (crypto.js:136:16)
    at Object.Hmac (crypto.js:134:12)
    at generateSignature (lib/utils.js:4:21)
    at generateQueryString (lib/utils.js:106:38)
    at Object.itemSearch (lib/index.js:9:15)
    at Context.<anonymous> (test/test.coffee:108:16)
  

  4) client.itemSearch(query, cb) when credentials are valid when callback is passed should return search results from amazon:
     TypeError: Not a buffer
    at TypeError (native)
    at new Hmac (crypto.js:136:16)
    at Object.Hmac (crypto.js:134:12)
    at generateSignature (lib/utils.js:4:21)
    at generateQueryString (lib/utils.js:106:38)
    at Object.itemSearch (lib/index.js:9:15)
    at Context.<anonymous> (test/test.coffee:118:16)

**Comment by masterT** [comment]
Hi,

You must pass valid Amazon Credentials in the process like this `npm test AWS_TAG=[your tag value] AWS_ID=[your id value] AWS_SECRET=[your secret value]`


**test/test.coffee** line **7**
```js
credentials =  
  awsTag: process.env.AWS_TAG
  awsId: process.env.AWS_ID
  awsSecret: process.env.AWS_SECRET
```

**Comment by donovanh** [comment]
Having a possibly related issue - I'm running the test as directed, with AWS_TAG etc in the test command, but seeing this output:

<img width="513" alt="screen shot 2016-01-14 at 08 58 46" src="https://cloud.githubusercontent.com/assets/853536/12319884/2161ddb0-ba9d-11e5-98fb-851f8587d52b.png">

Any ideas? :)
